# Permalinks
permalink: /:year/:title/

# Setup
title: Ryan Hedgecock
tagline: JetBrains Pages Theme
icon: /assets/images/icon.png
greeting: Hi I'm Ryan 👋
description: >-
  I made this theme, because I love the look and feel of Intellij code editors! ❤️<br>
  Have a look around, and use the template to create your own!
data-theme: light # default theme
baseurl: /JetBrains-Pages-Theme # change this to whatever baseurl you have. Could even just be '/'

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
sass:
  sass_dir: _sass
  style: compressed